# Generated by Django 5.0.2 on 2024-02-13 10:44

import django.core.validators
import django.db.models.deletion
import ptproject.models
import ptproject.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(max_length=100)),
                ('email', models.EmailField(default='default@example.com', max_length=70)),
                ('contact_message', models.TextField(blank=True, max_length=400, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=100)),
                ('session_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemberComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('photo', models.ImageField(upload_to='member_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default@example.com', max_length=70)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[ptproject.utils.num_validation])),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, validators=[ptproject.utils.alpha_only])),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, validators=[ptproject.utils.alpha_only])),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='State your name', max_length=100)),
                ('phonenumber', models.CharField(default='1234567890', max_length=15)),
                ('email', models.EmailField(default='your@mail.com', max_length=70)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male')),
                ('message', models.TextField(default='', max_length=300)),
                ('date', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('time', models.CharField(choices=[('AM', 'Before Noon'), ('PM', 'After Noon')], default='AM', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(default=ptproject.models.get_default_session, null=True, on_delete=django.db.models.deletion.CASCADE, to='ptproject.session')),
            ],
        ),
    ]
